version: '3.9'

services:
  tetris:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=tetrisdb
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=secret
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tetrisdb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    networks:
      - app-network
  redis:
    image: redis:latest
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
